[package]
name = "rusty-care-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
git-discover = "0.13.1"
git2 = "0.16.1"
time = "0.1.37"
tui = { package = "ratatui", version="0.20.1" }
