[package]
name = "rusty-care-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
docopt = "1.1.1"
git2 = "0.15.0"
serde = {version="1.0.145", features = ["derive"]}
structopt = "0.3.26"
time = "0.1.37"
